#fps_limit=0,62,78,91,118
#GraveDigger
#fps_limit=0,62,78,91,118,144
#Steambox
fps_limit=0,62,78,118
horizontal
legacy_layout=0
table_columns=20
fps
ram
vram
gpu_stats
gpu_power
gpu_temp
cpu_stats
cpu_power
cpu_temp
frametime=0
hud_no_margin
background_alpha=0.00
alpha=0.8
#GraveDigger
#font_size=18
#Steambox
font_size=28
#text_outline=0
#no_display
toggle_hud=Shift_R+F12
toggle_fps_limit=Shift_R+F1
hud_compact
