# AMD Ryzen 1-4
# edit 31.03.2025 NO Kernel 6.14!

#    sudo ln -s "$HOME/.config/sensors/zenpower.conf" /etc/sensors.d/

chip "zenpower-*"
    label in1 "CPU Core Voltage (SVI2)"
    label in2 "SOC Voltage (SVI2)"
    label temp1 "CPU Temperature (tDie)"
    label temp2 "CPU Temperature (tCtl)"
    label curr1 "CPU Core Current (SVI2)"
    label curr2 "SOC Current (SVI2)"
    label power1 "CPU Core Power (SVI2)"
        #compute power1 @ * 0.9, @ / 0.9
    label power2 "SOC Power (SVI2)"


werkstatt@Werkstatt:~$ uname -a
Linux Werkstatt 6.14.0-x64v3-xanmod1 #0~20250326.g70df074 SMP PREEMPT_DYNAMIC Wed Mar 26 00:48:30 UTC x86_64 x86_64 x86_64 GNU/Linux

werkstatt@Werkstatt:~$ sensors
iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:        +36.0°C  

nvme-pci-0100
Adapter: PCI adapter
Composite:    +32.9°C  (low  =  -5.2°C, high = +79.8°C)
                       (crit = +84.8°C)

amdgpu-pci-0400
Adapter: PCI adapter
vddgfx:      887.00 mV 
vddnb:         1.16 V  
edge:         +34.0°C  
PPT:          13.00 W  

nct6793-isa-0290
Adapter: ISA adapter
in0:                   616.00 mV (min =  +0.00 V, max =  +1.74 V)
in1:                     1.85 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in2:                     3.41 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in3:                     3.39 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in4:                   248.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:                   128.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:                   824.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in7:                     3.41 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in8:                     3.25 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in9:                     1.84 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in10:                  176.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in11:                  128.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in12:                    1.85 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in13:                    1.72 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in14:                  184.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
fan1:                     0 RPM  (min =    0 RPM)
fan2:                   993 RPM  (min =    0 RPM)
fan3:                     0 RPM  (min =    0 RPM)
fan4:                     0 RPM  (min =    0 RPM)
fan5:                     0 RPM  (min =    0 RPM)
SYSTIN:                +118.0°C  (high =  +0.0°C, hyst =  +0.0°C)  sensor = thermistor
CPUTIN:                 +45.5°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
AUXTIN0:                +35.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
AUXTIN1:               +109.0°C    sensor = thermistor
AUXTIN2:               +110.0°C    sensor = thermistor
AUXTIN3:               +110.0°C    sensor = thermistor
SMBUSMASTER 0:          +38.0°C  
PCH_CHIP_CPU_MAX_TEMP:   +0.0°C  
PCH_CHIP_TEMP:           +0.0°C  
PCH_CPU_TEMP:            +0.0°C  
PCH_MCH_TEMP:            +0.0°C  
Agent0 Dimm0 :           +0.0°C  
TSI0_TEMP:              +38.0°C  
TSI2_TEMP:             +3892314.0°C  
TSI3_TEMP:             +3892314.0°C  
TSI4_TEMP:             +3892314.0°C  
TSI5_TEMP:             +3892314.0°C  
TSI6_TEMP:             +3892314.0°C  
TSI7_TEMP:             +3892314.0°C  
intrusion0:            OK
intrusion1:            ALARM
beep_enable:           disabled

werkstatt@Werkstatt:~$ 
